CREATE TABLE IF NOT EXISTS tb_users (
	id BINARY(16) default (UUID_TO_BIN(UUID())),
	name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	password VARCHAR(60) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);